import { logger } from "../../infrastructure";
import dal from "./dal";

const response = async (_, args, { loaders }) => {
  logger.info(`Executing QUERY: response | params : ${JSON.stringify(args)}`);
  const response = await loaders.responses.load(args.id);
  logger.debug(`Response generated by dataloader: obj -> ${JSON.stringify(response)}`);
  return Array.isArray(response) ? response[0] : response;
};
const responses = async (_, { limit, next }) => {
  logger.info(`Executing QUERY: responses | NO params `);
  return await dal.searchAllResponses(limit, next);
};

export default { response, responses };
