import { logger } from "../../infrastructure";
import dal from "./dal";

const response = async (_, args, { loaders }) => {
  logger.info(`Executing QUERY: response | params : ${JSON.stringify(args)}`);
  const response = await loaders.responses.load(args.id);
  logger.debug(`Response generated by dataloader: obj -> ${JSON.stringify(response)}`);
  return response;
};
const responses = async () => {
  logger.info(`Executing QUERY: responses | NO params `);
  return await dal.searchAllResponses();
};

export default { response, responses };
